my_list = [11,22,33,44,55]
print(my_list)
my_list.append(66)
print(my_list)
my_list.extend([66,77,88])
print(my_list)
my_list.insert(2,99)
print(my_list)
my_list.remove(22)
print(my_list)
my_list.pop()
print(my_list)
my_list.index(33)
print(my_list)
my_list.count(55)
print(my_list)
my_list.reverse()
print(my_list)
my_list.copy()
print(my_list)
my_list.clear()
print(my_list)
# ----------------------------------
my_tuple = (11,22,33,44,55,11)
print(my_tuple)
print(my_tuple.count(11))
print(my_tuple.index(33))
print(len(my_tuple))


